@echo off
echo Starting AI Interview Platform...
echo.
echo Starting Backend Server...
start "Backend Server" cmd /k "cd flask\Emotion_detection_with_CNN-main && call new_env\Scripts\activate.bat && python app.py"
timeout /t 3 /nobreak >nul
echo.
echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd frontend && npm run dev"
echo.
echo Both servers are starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:5173
